config/routes.rb
Rails.application.routes.draw do
  namespace :admin do 
    resources :products
    resources :categories
    resources :shops
    resources :dashboard, only: [:index] do
      collection do
        get "back_office", to: "dashboard#back_office"
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "landing#index"
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :products, through: :categories
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  layout 'admin/base'

  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :address, :email, :description, :payment_option, :payment_details, :activation_code, :activated, :activated_at)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :address, :email, :description, :payment_option, :payment_details, :activation_code, :activated, :activated_at)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/admin/shops/_form.html.erb
<div class="flex items-center justify-center p-12 mt-6 mx-6">
  <div class="mx-auto w-full max-w-[550px]">
      <%= form_with model: [:admin, @shop] do |form| %>
      <div>
        <%= form.label :name, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :name, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div>
        <%= form.label :address, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :address, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div>
        <%= form.label :email, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :email, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div>
        <%= form.label :description, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :description, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div>
        <%= form.label :payment_option, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :payment_option, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div>
        <%= form.label :payment_details, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :payment_details, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div>
        <%= form.label :activation_code, style: "display: block", class: "mb-3 block text-base font-medium text-[#07074D]" %>
        <%= form.text_field :activation_code, class: "w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md" %>
      </div>

      <div class="mt-4">
        <%= form.submit "Update Shop", class: "flex items-center px-3 py-2 bg-blue-600 text-white text-sm font-medium rounded-md hover:bg-blue-500 focus:outline-none focus:bg-blue-500" %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Name:</strong>
    <%= shop.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= shop.address %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= shop.email %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= shop.description %>
  </p>

  <p>
    <strong>Payment option:</strong>
    <%= shop.payment_option %>
  </p>

  <p>
    <strong>Payment details:</strong>
    <%= shop.payment_details %>
  </p>

  <p>
    <strong>Activation code:</strong>
    <%= shop.activation_code %>
  </p>

  <p>
    <strong>Activated:</strong>
    <%= shop.activated %>
  </p>

  <p>
    <strong>Activated at:</strong>
    <%= shop.activated_at %>
  </p>

</div>

app/views/admin/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", admin_shops_path %>
</div>

app/views/admin/shops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shops</h1>

<div id="shops">
  <% @shops.each do |shop| %>
    <%= render shop %>
    <p>
      <%#= link_to "Show this shop", shop %>
    </p>
  <% end %>
</div>

<%= link_to "New shop", new_admin_shop_path %>

app/views/admin/shops/new.html.erb
<h1>New shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Back to shops", admin_shops_path %>
</div>

app/views/admin/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shop %>

<div>
  <%= link_to "Edit this shop", edit_admin_shop_path(@shop) %> |
  <%= link_to "Back to shops", admin_shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>