config/routes.rb
Rails.application.routes.draw do
  namespace :admin do 
    resources :products
    resources :categories
    resources :shops
    resources :dashboard, only: [:index] do
      collection do
        get "back_office", to: "dashboard#back_office"
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "landing#index"
end

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Duka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script defer src="https://unpkg.com/alpinejs@3.10.2/dist/cdn.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" />
  </head>

  <body>
   <div>

      <%= render "shared/header" %>

      <div class="container mx-auto p-6">
        <!-- page -->
        <main class="min-h-screen w-full bg-gray-100 text-gray-700" x-data="layout">
            <!-- header page -->
            <header class="flex w-full items-center justify-between border-b-2 border-gray-200 bg-white p-2">        <!-- logo -->
                Welcome, <%#= current_user&.email %>
            </header>

            <div class="flex">
                <!-- aside -->
                <aside class="flex w-72 flex-col space-y-2 border-r-2 border-gray-200 bg-white p-2" style="height: 90.5vh"
                    x-show="asideOpen">

                    <%= link_to back_office_admin_dashboard_index_path, class:"flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
                        <span class="text-2xl"><i class="bx bx-money"></i></span>
                        <span>Home</span>
                    <% end %>

                    <%= link_to "#", class:"flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
                        <span class="text-2xl"><i class="bx bx-user"></i></span>
                        <span>Profile</span>
                    <% end %>

                    <%= link_to admin_shops_path, class:"flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
                        <span class="text-2xl"><i class="bx bx-home"></i></span>
                        <span>Shop</span>
                    <% end %>

                    <%= link_to "#", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
                        <span class="text-2xl"><i class="bx bx-cart"></i></span>
                        <span>Category</span>
                    <% end %>

                    <%= link_to "#", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
                        <span class="text-2xl"><i class="bx bx-shopping-bag"></i></span>
                        <span>Product</span>
                    <% end %>

                    <%= link_to "#", class: "flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600" do %>
                        <span class="text-2xl"><i class="bx bx-heart"></i></span>
                        <span>Order</span>
                    <% end %>
                </aside>
                <div class="w-full p-4">
                    <%= yield %>
                </div>
            </div>
        </main>

        <script>
            document.addEventListener("alpine:init", () => {
                Alpine.data("layout", () => ({
                    profileOpen: false,
                    asideOpen: true,
                }));
            });
        </script>  
      </div>
   </div>
  </body>
</html>